apiVersion: v1
kind: Service
metadata:
    name: "onlinerestaurantaks-eda6"
    labels:
        app: "onlinerestaurantaks-eda6"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "onlinerestaurantaks-eda6"